import { ArrowLeft, ArrowRight } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { site, treatments } from "@/data/site";
import { Breadcrumbs, PageShell, SEO, SectionTitle, WhatsAppButton } from "@/components/SiteComponents";

export default function TreatmentDetailPage() {
  const { slug } = useParams();
  const treatment = treatments.find((item) => item.slug === slug) ?? treatments[0];
  return <PageShell>
    <SEO title={`${treatment.name} | Tratamentos`} description={treatment.description} path={`/tratamentos/${treatment.slug}`} />
    <section className="relative flex min-h-[440px] items-end overflow-hidden bg-[#244c36] pt-[76px]"><img src={treatment.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-40" width="1600" height="900" /><div className="absolute inset-0 bg-[#1d3c2a]/65" /><div className="relative mx-auto w-full max-w-7xl px-5 py-20 lg:px-8"><p className="eyebrow text-[#e2c58f]">Tratamentos</p><h1 className="mt-4 max-w-3xl font-serif text-4xl leading-tight text-white sm:text-5xl lg:text-6xl">{treatment.name}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#edf0e7]">{treatment.description}</p></div></section>
    <Breadcrumbs current={treatment.name} />
    <section className="px-5 py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_0.8fr]"><article><SectionTitle eyebrow="Cuidado individualizado" title={treatment.name} text={treatment.description} /><div className="mt-8 space-y-5">{treatment.information.map((paragraph) => <p key={paragraph} className="leading-8 text-[#5b675b]">{paragraph}</p>)}</div>{treatment.slug === "internacao" && <div className="mt-8 rounded-2xl border border-[#dfe4d9] bg-[#f6f5ed] p-6"><h2 className="font-serif text-2xl text-[#244c36]">Orientação responsável</h2><p className="mt-3 text-sm leading-7 text-[#5b675b]">A internação voluntária ou involuntária deve observar a legislação aplicável. Fale com a equipe para receber orientação sobre a situação.</p></div>}<div className="mt-9 flex flex-wrap gap-3"><WhatsAppButton /><Link to="/tratamentos" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-[#b9c5b5] px-5 text-sm font-semibold text-[#244c36] hover:bg-[#edf0e8]"><ArrowLeft size={16} /> Voltar para tratamentos</Link></div></article><div><img src={treatment.image} alt="Registro da propriedade do Espaço Village" className="aspect-[4/3] w-full rounded-2xl object-cover" width="1000" height="750" loading="lazy" /><div className="mt-7 rounded-2xl bg-[#edf0e8] p-6"><h2 className="font-serif text-2xl text-[#244c36]">Fale com nossa equipe</h2><p className="mt-3 text-sm leading-7 text-[#5b675b]">{site.whatsapp.display} — WhatsApp</p><WhatsAppButton className="mt-5">Conversar pelo WhatsApp</WhatsAppButton></div></div></div></section>
    <section className="bg-[#e9e6d7] px-5 py-14 lg:px-8"><div className="mx-auto max-w-5xl"><SectionTitle title="Conheça também" text="Veja os outros tratamentos apresentados pelo Espaço Village." /><div className="mt-7 flex flex-wrap gap-3">{treatments.filter((item) => item.slug !== treatment.slug).map((item) => <Link key={item.slug} to={`/tratamentos/${item.slug}`} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#b9c5b5] bg-white px-5 text-sm font-semibold text-[#244c36] hover:bg-[#edf0e8]">{item.name}<ArrowRight size={16} /></Link>)}</div></div></section>
  </PageShell>;
}
