import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Link, NavLink } from "react-router-dom";
import { ArrowRight, Check, ChevronDown, Clock3, ExternalLink, MapPin, Menu, Phone, X } from "lucide-react";
import { galleryCategories, faqItems, navItems, site, type GalleryCategory, type Treatment } from "@/data/site";

export function SEO({ title, description, path = "" }: { title: string; description: string; path?: string }) {
  useEffect(() => {
    document.title = `${title} | Espaço Village`;
    const set = (name: string, content: string, property = false) => {
      const selector = property ? `meta[property="${name}"]` : `meta[name="${name}"]`;
      let tag = document.head.querySelector(selector) as HTMLMetaElement | null;
      if (!tag) {
        tag = document.createElement("meta");
        tag.setAttribute(property ? "property" : "name", name);
        document.head.appendChild(tag);
      }
      tag.content = content;
    };
    set("description", description);
    set("og:title", title, true);
    set("og:description", description, true);
    set("og:type", "website", true);
    set("og:url", `${site.canonical}${path}`, true);
    set("og:image", `${site.canonical}/assets/clinica-jardim.jpeg`, true);
    set("og:locale", "pt_BR", true);
    set("twitter:card", "summary_large_image");
    set("twitter:title", title);
    set("twitter:description", description);
    set("twitter:image", `${site.canonical}/assets/clinica-jardim.jpeg`);
    let canonical = document.head.querySelector("link[rel=canonical]") as HTMLLinkElement | null;
    if (!canonical) {
      canonical = document.createElement("link");
      canonical.rel = "canonical";
      document.head.appendChild(canonical);
    }
    canonical.href = `${site.canonical}${path}`;
  }, [title, description, path]);
  return null;
}

export function Header() {
  const [open, setOpen] = useState(false);
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-[#d8ddcf]/80 bg-[#fbfaf5]/95 backdrop-blur" aria-label="Cabeçalho principal">
    <div className="mx-auto flex min-h-[76px] max-w-7xl items-center justify-between gap-2 px-3 sm:gap-4 sm:px-5 lg:px-8">
      <Link to="/" onClick={() => setOpen(false)} className="flex min-w-0 items-center gap-2 sm:gap-3" aria-label="Espaço Village, página inicial">
        <img src="/assets/image-removebg-preview.png" alt="Espaço Village" className="h-12 w-auto shrink-0 object-contain sm:h-14" width="180" height="80" />
        <span className="min-w-0 border-l border-[#cdd7c8] pl-2 text-[10px] leading-4 text-[#526153] sm:pl-3 sm:text-xs sm:leading-5"><strong className="block whitespace-nowrap font-semibold tracking-[0.08em] text-[#244c36] sm:tracking-[0.12em]">ESPAÇO VILLAGE</strong><span className="max-[359px]:hidden">Clínica • Guapimirim/RJ</span></span>
      </Link>
      <nav className="hidden items-center gap-3 xl:flex" aria-label="Navegação principal">{navItems.map(([label, href]) => <NavLink key={href} to={href} className={({ isActive }) => `text-[13px] font-medium tracking-wide transition-colors ${isActive ? "text-[#244c36]" : "text-[#526153] hover:text-[#244c36]"}`}>{label}</NavLink>)}</nav>
      <div className="hidden items-center gap-4 xl:flex"><a href={site.phoneHref} className="hidden items-center gap-2 whitespace-nowrap text-sm font-medium text-[#244c36] 2xl:flex" aria-label={`Telefone ${site.phone}`}><Phone size={15} />{site.phone}</a><ContactButton /></div>
      <button className="shrink-0 rounded-lg p-3 text-[#244c36] hover:bg-[#edf0e8] xl:hidden" onClick={() => setOpen(!open)} aria-label={open ? "Fechar menu" : "Abrir menu"} aria-expanded={open}>{open ? <X /> : <Menu />}</button>
    </div>
    {open && <nav className="max-h-[calc(100vh-76px)] overflow-y-auto border-t border-[#d8ddcf] bg-[#fbfaf5] px-5 py-5 xl:hidden" aria-label="Menu mobile"><a href={site.phoneHref} className="mb-3 flex items-center gap-2 border-b border-[#e5e8df] pb-4 text-sm font-semibold text-[#244c36]"><Phone size={16} />{site.phone}</a>{navItems.map(([label, href]) => <NavLink key={href} to={href} onClick={() => setOpen(false)} className="block border-b border-[#e5e8df] py-3 text-sm font-medium text-[#244c36]">{label}</NavLink>)}<div className="pt-5"><ContactButton onClick={() => setOpen(false)}>Fale Conosco</ContactButton></div></nav>}
  </header>;
}

export function Footer() {
  return <footer className="bg-[#244c36] text-[#f5f3e9]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><img src="/assets/image-removebg-preview.png" alt="Espaço Village" className="mb-5 h-16 w-auto brightness-0 invert" width="180" height="80" /><p className="max-w-xs text-sm leading-7 text-[#d8e0d1]">ESPAÇO VILLAGE<br />Clínica • Guapimirim/RJ</p><p className="mt-3 text-sm text-[#d8e0d1]">Atendimento 24 horas</p></div><div><h2 className="mb-4 font-serif text-lg">Navegue</h2><div className="grid gap-2 text-sm text-[#d8e0d1]">{navItems.map(([label, href]) => <Link key={href} to={href} className="hover:text-white">{label}</Link>)}<Link to="/politica-de-privacidade" className="hover:text-white">Política de privacidade</Link><Link to="/termos-de-uso" className="hover:text-white">Termos de uso</Link></div></div><div><h2 className="mb-4 font-serif text-lg">Endereços</h2><div className="grid gap-4 text-sm leading-6 text-[#d8e0d1]"><Link to="/unidades/guapimirim" className="hover:text-white"><strong className="font-semibold text-white">Guapimirim</strong><br />{site.addressGuapi}</Link><Link to="/unidades/copacabana" className="hover:text-white"><strong className="font-semibold text-white">Copacabana</strong><br />{site.addressCopa}</Link><span><strong className="font-semibold text-white">Núcleo Integrado</strong><br />Recreio dos Bandeirantes — Rio de Janeiro</span></div></div><div><h2 className="mb-4 font-serif text-lg">Fale conosco</h2><a href={site.phoneHref} className="flex items-center gap-2 text-sm text-[#e7eddf]"><Phone size={15} /> {site.phone}</a><p className="mt-3 text-sm text-[#d8e0d1]">Atendimento 24 horas</p></div></div><div className="border-t border-[#54715c] px-5 py-5 text-center text-xs text-[#d8e0d1] lg:px-8">© 2026 Espaço Village. Todos os direitos reservados.</div></footer>;
}

export function ContactButton({ children = "Fale Conosco", onClick }: { children?: ReactNode; onClick?: () => void }) { return <Link to="/contato" onClick={onClick} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-[#c2a16a] px-5 text-sm font-semibold text-[#203d2b] transition hover:bg-[#d5b87f] focus:outline-none focus:ring-2 focus:ring-[#c2a16a] focus:ring-offset-2">{children}<ArrowRight size={16} /></Link>; }
export function CTA({ title = "Vamos conversar?", text = "Nossa equipe está disponível para acolher sua mensagem." }: { title?: string; text?: string }) { return <section className="bg-[#e9e6d7] px-5 py-16 lg:px-8"><div className="mx-auto flex max-w-5xl flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><p className="eyebrow">Espaço Village</p><h2 className="mt-3 font-serif text-3xl text-[#244c36] md:text-4xl">{title}</h2><p className="mt-3 max-w-xl text-[#5b675b]">{text}</p></div><ContactButton>Entrar em contato</ContactButton></div></section>; }
export function Hero({ eyebrow, title, text, image = "/assets/clinica-jardim.jpeg", children }: { eyebrow: string; title: string; text: string; image?: string; children?: ReactNode }) { return <section className="relative flex min-h-[470px] items-end overflow-hidden bg-[#244c36] pt-[76px]"><img src={image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-45" width="1600" height="900" /><div className="absolute inset-0 bg-[#1d3c2a]/45" /><div className="relative mx-auto w-full max-w-7xl px-5 py-20 lg:px-8"><p className="eyebrow text-[#e2c58f]">{eyebrow}</p><h1 className="mt-4 max-w-3xl font-serif text-4xl leading-tight text-white sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#edf0e7]">{text}</p>{children && <div className="mt-8">{children}</div>}</div></section>; }
export function SectionTitle({ eyebrow, title, text, center = false }: { eyebrow?: string; title: string; text?: string; center?: boolean }) { return <div className={center ? "mx-auto max-w-2xl text-center" : "max-w-2xl"}>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2 className="mt-3 font-serif text-3xl leading-tight text-[#244c36] md:text-4xl">{title}</h2>{text && <p className="mt-4 leading-7 text-[#5b675b]">{text}</p>}</div>; }

export function PageShell({ children }: { children: ReactNode }) { return <><Header /><main>{children}</main><Footer /><a href={site.phoneHref} className="fixed bottom-5 right-5 z-40 flex h-14 w-14 items-center justify-center rounded-full bg-[#c2a16a] text-[#203d2b] shadow-lg transition hover:scale-105" aria-label={`Ligar para ${site.phone}`}><Phone size={22} /></a><CookieBanner /></>; }
function CookieBanner() { const [visible, setVisible] = useState(() => !localStorage.getItem("cookie-preference")); if (!visible) return null; const decide = (value: string) => { localStorage.setItem("cookie-preference", value); setVisible(false); }; return <div className="fixed inset-x-4 bottom-4 z-50 flex flex-col gap-4 rounded-2xl border border-[#d8ddcf] bg-[#fbfaf5] p-5 shadow-xl sm:flex-row sm:items-center sm:justify-between"><p className="max-w-2xl text-sm leading-6 text-[#526153]">Usamos apenas o armazenamento local necessário para lembrar sua preferência sobre cookies não essenciais. Saiba mais na <Link className="font-medium text-[#244c36] underline" to="/politica-de-privacidade">política de privacidade</Link>.</p><div className="flex shrink-0 gap-2"><button onClick={() => decide("rejected")} className="rounded-full border border-[#b9c5b5] px-4 py-2 text-sm text-[#244c36]">Recusar</button><button onClick={() => decide("accepted")} className="rounded-full bg-[#244c36] px-4 py-2 text-sm text-white">Aceitar</button></div></div>; }

export function TeamCard({ name, role, bio }: { name: string; role: string; bio?: string }) { return <article className="rounded-2xl border border-[#dfe4d9] bg-white p-6"><div className="mb-5 flex h-24 w-24 items-center justify-center rounded-full bg-[#e9e6d7] text-[#6f806d]" aria-label="Foto da equipe não disponível"><span className="font-serif text-3xl">EV</span></div><h3 className="font-serif text-xl text-[#244c36]">{name}</h3><p className="mt-1 text-sm font-medium text-[#a17c46]">{role}</p>{bio && <p className="mt-4 text-sm leading-7 text-[#5b675b]">{bio}</p>}</article>; }
export function UnitCard({ title, address, href, image, children }: { title: string; address: string; href: string; image?: string; children?: ReactNode }) { return <article className="overflow-hidden rounded-2xl border border-[#dfe4d9] bg-white">{image && <img src={image} alt="" className="aspect-[16/8] w-full object-cover" loading="lazy" width="800" height="400" />}<div className="p-6"><p className="eyebrow">Unidade</p><h3 className="mt-2 font-serif text-2xl text-[#244c36]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#5b675b]">{address}</p>{children || <Link to={href} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#244c36]">Conhecer unidade <ArrowRight size={16} /></Link>}</div></article>; }
export function TreatmentCard({ treatment }: { treatment: Treatment }) { return <article className="rounded-2xl border border-[#dfe4d9] bg-white p-7"><h3 className="font-serif text-xl text-[#244c36]">{treatment.name}</h3><p className="mt-3 text-sm leading-7 text-[#5b675b]">{treatment.description}</p><Link to={`/tratamentos/${treatment.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#244c36]">{treatment.cta}<ArrowRight size={16} /></Link></article>; }
export function Gallery({ limit }: { limit?: number }) { const [active, setActive] = useState<"Todos" | GalleryCategory>("Todos"); const filtered = site.photos.filter((photo) => active === "Todos" || photo.category === active).slice(0, limit || site.photos.length); return <div><div className="mb-8 flex flex-wrap gap-2" role="group" aria-label="Filtros da galeria">{galleryCategories.map((category) => <button key={category} type="button" onClick={() => setActive(category)} aria-pressed={active === category} className={`rounded-full border px-4 py-2 text-sm transition ${active === category ? "border-[#244c36] bg-[#244c36] text-white" : "border-[#b9c5b5] text-[#244c36] hover:bg-[#edf0e8]"}`}>{category}</button>)}</div>{filtered.length ? <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{filtered.map((photo, i) => <figure key={photo.src} className={`overflow-hidden rounded-xl ${i === 0 ? "col-span-2 row-span-2" : ""}`}><img src={photo.src} alt={photo.alt} loading={i === 0 ? "eager" : "lazy"} className="h-full min-h-36 w-full object-cover transition duration-500 hover:scale-105" width="800" height="600" /></figure>)}</div> : <div className="rounded-2xl border border-dashed border-[#b9c5b5] bg-[#f6f5ed] p-10 text-center"><p className="font-medium text-[#244c36]">Imagem profissional não disponível</p><p className="mt-2 text-sm text-[#5b675b]">Ainda não há registro confirmado para a categoria {active}.</p></div>}</div>; }
export function FAQ() { const [active, setActive] = useState<number | null>(null); return <div className="divide-y divide-[#dfe4d9] rounded-2xl border border-[#dfe4d9] bg-white">{faqItems.map((item, i) => <div key={item.question}><button className="flex w-full items-center justify-between gap-5 p-5 text-left font-medium text-[#244c36]" onClick={() => setActive(active === i ? null : i)} aria-expanded={active === i}>{item.question}<ChevronDown className={`shrink-0 transition ${active === i ? "rotate-180" : ""}`} size={18} /></button>{active === i && <p className="px-5 pb-5 text-sm leading-7 text-[#5b675b]">{item.answer}</p>}</div>)}</div>; }
export function Map({ query }: { query: string }) { const mapsUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`; return <div><iframe title={`Mapa: ${query}`} src={`https://www.google.com/maps?q=${encodeURIComponent(query)}&output=embed`} className="h-80 w-full rounded-2xl border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><a href={mapsUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-[#244c36]">Como chegar <ExternalLink size={15}/></a></div>; }
export function ContactForm() { const [sent, setSent] = useState(false); const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setSent(true); }; if (sent) return <div className="rounded-2xl border border-[#c7d8c2] bg-[#edf4e9] p-8" role="status"><Check className="text-[#244c36]" /><h3 className="mt-4 font-serif text-2xl text-[#244c36]">Mensagem recebida localmente</h3><p className="mt-2 text-sm leading-7 text-[#526153]">Obrigado pelo contato. Esta confirmação é apenas local: o formulário não envia nem armazena dados. Para falar conosco, ligue para {site.phone}.</p></div>; return <form onSubmit={submit} className="space-y-5 rounded-2xl border border-[#dfe4d9] bg-white p-6 sm:p-8"><div><label htmlFor="name" className="label">Nome</label><input id="name" name="name" required autoComplete="name" className="field" /></div><div><label htmlFor="phone" className="label">Telefone</label><input id="phone" name="phone" type="tel" required autoComplete="tel" className="field" /></div><div><label htmlFor="email" className="label">E-mail</label><input id="email" name="email" type="email" required autoComplete="email" className="field" /></div><div><label htmlFor="subject" className="label">Assunto</label><input id="subject" name="subject" required className="field" /></div><div><label htmlFor="message" className="label">Mensagem</label><textarea id="message" name="message" required rows={5} className="field resize-none" /></div><label className="flex items-start gap-3 text-sm leading-6 text-[#526153]"><input type="checkbox" required className="mt-1 h-4 w-4 accent-[#244c36]" />Li e concordo com a <Link to="/politica-de-privacidade" className="text-[#244c36] underline">Política de Privacidade.</Link></label><button className="inline-flex min-h-11 items-center justify-center rounded-full bg-[#244c36] px-6 text-sm font-semibold text-white hover:bg-[#315d43]" type="submit">Enviar mensagem</button><p className="text-xs text-[#748074]">Não informe dados clínicos ou sensíveis neste formulário.</p></form>; }

export function Breadcrumbs({ current }: { current: string }) { return <nav aria-label="Breadcrumb" className="mx-auto max-w-7xl px-5 pt-8 text-xs text-[#718071] lg:px-8"><Link to="/" className="hover:text-[#244c36]">Início</Link><span className="mx-2">/</span><span>{current}</span></nav>; }
export function InfoStrip() { return <div className="grid gap-5 border-y border-[#dfe4d9] py-7 sm:grid-cols-3"><div className="flex items-center gap-3"><MapPin className="text-[#a17c46]" size={20}/><span className="text-sm text-[#526153]">Guapimirim · RJ</span></div><div className="flex items-center gap-3"><Clock3 className="text-[#a17c46]" size={20}/><span className="text-sm text-[#526153]">Atendimento 24 horas</span></div><div className="flex items-center gap-3"><Phone className="text-[#a17c46]" size={20}/><a href={site.phoneHref} className="text-sm text-[#526153]">{site.phone}</a></div></div>; }
